_BASE_: Base-PointRend-Semantic-FPN.yaml
MODEL:
  # WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/PointRend/SemanticSegmentation/pointrend_semantic_R_101_FPN_1x_cityscapes/202576688/model_final_cf6ac1.pkl
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    NUM_CLASSES: 4
    IGNORE_VALUE: 255
  POINT_HEAD:
    NUM_CLASSES: 4
    TRAIN_NUM_POINTS: 2048
    SUBDIVISION_NUM_POINTS: 8192
DATASETS:
  TRAIN: ("proj_train",)
  TEST: ("proj_val",)
SOLVER:
  BASE_LR: 0.01
  STEPS: (1000, 3000)
  MAX_ITER: 12000
  IMS_PER_BATCH: 3
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 0.80
  COLOR_AUG_SSD: False
DATALOADER:
  NUM_WORKERS: 2
